App/OnlineStore/OnlineStore/Controllers/SuperuserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Data;
using OnlineStore.Models.StaticModels;
using OnlineStore.Models.SuperuserViewModel;
using OnlineStore.Models.SuperuserViewModel.ChartViewModels;
using OnlineStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Controllers
{
    public class SuperuserController : Controller
    {
        private readonly OnlineStore_DbContext db;
        //private readonly int userId;
        public SuperuserController(OnlineStore_DbContext db)
        {
            this.db = db;
            //userId = int.Parse(User.Claims.First().Value);
        }
        #region PurchaseHistory

        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> EditPurchaseHistory()
        {
            int userId = int.Parse(User.Claims.First().Value);

            List<PurchaseHistory> purchaseHistories = await db.PurchaseHistories.ToListAsync();
            List<User> users = await db.Users.Where(u => u.Id != userId).ToListAsync();
            List<Product> products = await db.Products.Include(p => p.Category).Include(p => p.ProductCharacteristics).ToListAsync();
            List<ProductVM> productVMs = new();

            foreach (Product product in products)
            {
                productVMs.Add(
                    new ProductVM
                    {
                        Id = product.Id,
                        ProductCharacteristics = product.ProductCharacteristics.Select(pc => pc.CharacteristicId).ToList(),
                        Category = product.Category,
                        CategoryId = product.CategoryId,
                        Description = product.Description,
                        Name = product.Name,
                        OnSale = product.OnSale,
                        Price = product.Price,
                        Rating = product.Rating,
                    });
            }

            var editPurchaseHistoryVM = new EditPurchaseHistoryVM
            {
                Products = productVMs,
                PurchaseHistories = purchaseHistories,
                Users = users,
            };
            IndexMenuVM.Categorys = db.Categories.Where(c => c.CategoryId == null && c.OnSale == true).Include(c => c.InverseCategoryNavigation).ToList();
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(editPurchaseHistoryVM);
        }

        [Authorize(Roles = "superuser")]
        [HttpPost]
        public async Task<IActionResult> EditPurchaseHistory(PurchaseHistory purchaseHistory)
        {

            if (purchaseHistory.Id != 0)
            {
                db.Entry(purchaseHistory).State = EntityState.Modified;
            }
            else
            {
                await db.PurchaseHistories.AddAsync(purchaseHistory);
            }
            await db.SaveChangesAsync();
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditPurchaseHistory");
        }
        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> RemovePurchaseHistory(PurchaseHistory purchaseHistory)
        {

            if (purchaseHistory.Id != 0)
            {
                db.Remove(purchaseHistory);
                await db.SaveChangesAsync();
            }
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditPurchaseHistory");
        }
        #endregion

        #region User

        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> EditUser()
        {
            int userId = int.Parse(User.Claims.First().Value);
            List<User> users = await db.Users.Where(u => u.Id != userId).ToListAsync();
            List<Role> roles = await db.Roles.ToListAsync();

            var editUserVM = new EditUserVM
            {
                Users = users,
                Roles = roles,
            };
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(editUserVM);
        }

        [Authorize(Roles = "superuser")]
        [HttpPost]
        public async Task<IActionResult> EditUser(User user)
        {

            if (user.Id != 0)
            {
                db.Entry(user).State = EntityState.Modified;
            }
            else
            {
                await db.Users.AddAsync(user);
            }
            await db.SaveChangesAsync();
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditUser");
        }
        #endregion

        #region Role
        //[Authorize(Roles = "superuser")]
        //[HttpPost]
        //public async Task<IActionResult> EditUser(Role role)
        //{

        //    if (role.Id != 0)
        //    {
        //        db.Entry(role).State = EntityState.Modified;
        //    }
        //    else
        //    {
        //        await db.Roles.AddAsync(role);
        //    }
        //    await db.SaveChangesAsync();

        //    return RedirectToAction("AdminAccount", new AdminVM { Status = "PurchaseHistory" });
        //}
        //[Authorize(Roles = "superuser")]
        //[HttpGet]
        //public async Task<IActionResult> RemovePurchaseHistory(Role role)
        //{

        //    if (role.Id != 0)
        //    {
        //        var users = db.Users.Where(u => u.RoleId == role.Id);
        //        if (users != null)
        //        {
        //            db.Users.RemoveRange(users);
        //            db.Remove(role);
        //            await db.SaveChangesAsync();
        //        }
        //    }


        //    return RedirectToAction("AdminAccount", new AdminVM { Status = "Role" });
        //}
        #endregion

        #region MonitorDatabase
        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> ShowMonitorDatabase()
        {
            List<MonitorDatabase> monitorDatabase = await db.MonitorDatabases.ToListAsync();
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(monitorDatabase);
        }
        #endregion

        #region Analytics
        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> Analytics(DateTime startDate, DateTime endDate)
        {
            if (startDate > endDate)
            {
                ViewData["Ex"] = "Начальная дата не может быть больше конечной";
                return View(new AnalyticsVM { ShowIs = false });
            }

            if (startDate == default || endDate == default)
            {
                startDate = DateTime.Now.AddYears(-1);
                endDate = DateTime.Now;
            }

            List<PurchaseHistory> purchaseHistories = await db.PurchaseHistories.
                Where(p => p.DatePurchase >= startDate && p.DatePurchase <= endDate)
                .Include(p => p.User).Include(p => p.Product).OrderBy(p => p.DatePurchase).ToListAsync();


            var dates = purchaseHistories
                .GroupBy(p => new { p.DatePurchase.Month, p.DatePurchase.Year })
                .Select(p => p.FirstOrDefault().DatePurchase)
                .OrderBy(p => p)
                .ToList();

            var prices = new List<decimal>();
            var amountProducts = new List<int>();
            foreach (var date in dates)
            {
                decimal price = 0.00m;
                foreach (var item in purchaseHistories.Where(p => p.DatePurchase.Month == date.Month && p.DatePurchase.Year == date.Year))
                {
                    price += item.Product.Price * item.AmountProduct;
                }
                prices.Add(price);

                int amountProduct = 0;
                var pH = purchaseHistories.Where(p => p.DatePurchase.Month == date.Month && p.DatePurchase.Year == date.Year);
                foreach (var item in pH)
                {
                    amountProduct += item.AmountProduct;
                }
                amountProducts.Add(amountProduct);
            }



            CharVM charVM = new() { Dates = dates.Select(d => d.ToString("Y")).ToList(), Amounts = amountProducts, Prices = prices };

            var analyticsVM = new AnalyticsVM
            {
                EndDate = endDate,
                StartDate = startDate,
                PurchaseHistories = purchaseHistories,
                ShowIs = true,
                CharVM = charVM
            };
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(analyticsVM);
        }
        #endregion

        #region Report
        [Authorize(Roles = "superuser")]
        [HttpGet]
        public async Task<IActionResult> Report(ReportVM reportVM)
        {
            if (reportVM.StartDate > reportVM.EndDate)
            {
                ViewData["Ex"] = "Начальная дата не может быть больше конечной";
                return RedirectToAction("Analytics");
            }

            List<PurchaseHistory> purchaseHistories = await db.PurchaseHistories.
                Where(p => p.DatePurchase >= reportVM.StartDate && p.DatePurchase <= reportVM.EndDate)

App/OnlineStore/OnlineStore/Views/Superuser/Analytics.cshtml
@model AnalyticsVM
@{
    Layout = "_LayoutAdmin";
    int anA = 0;
    int anI = 1;
}

<div class="tab-pane fade mx-auto col-md-10 show active" id="analytics">
    <h4>Аналитика</h4>

    <div class="table_page">
        <form method="get" asp-action="Analytics" asp-controller="Superuser">
            <table>
                <thead>
                    <tr>
                        <th>Начальная дата</th>
                        <th>Конечная дата</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="date" autocomplete="off" required class="table-input-text" name="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")">
                        </td>
                        <td>
                            <input type="date" autocomplete="off" required class="table-input-text" name="EndDate" value="@Model.EndDate.ToString("yyyy-MM-dd")">
                        </td>
                        <td><input class="btn-tb" type="submit" value="Показать" /></td>
                    </tr>
                </tbody>
            </table>
        </form>
        <h4>@ViewData["Ex"]</h4>
    </div>
    @if (Model.ShowIs == true && Model.PurchaseHistories.Count > 0)
    {
        <div class="table_page" style="overflow-x: auto;height: 400px;">
            <form method="get" id="formChartId" asp-action="Report" asp-controller="Superuser">
                <input type="date" hidden name="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")" />
                <input type="date" hidden name="EndDate" value="@Model.EndDate.ToString("yyyy-MM-dd")"/>
                <table>
                    <thead>
                        <tr>
                            <th>№</th>
                            <th>Клиент</th>
                            <th>Продукт</th>
                            <th>Количество</th>
                            <th>Дата покупки</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PurchaseHistories)
                        {

                            <tr id="trPurId-@anA">
                                <td>@anI</td>
                                <td>
                                    <input type="text" autocomplete="off" required readonly disabled class="table-input-text" value="@item.User.LastName @item.User.FirstName">
                                </td>
                                <td>
                                    
                                    <input type="text" autocomplete="off" required readonly disabled class="table-input-text" name="PurchaseHistories[@anA].Product.Name" value="@item.Product.Name">
                                </td>
                                <td>
                                    <input type="text" autocomplete="off" required readonly disabled class="table-input-text" name="PurchaseHistories[@anA].AmountProduct" value="@item.AmountProduct">
                                </td>
                                <td><input type="date" autocomplete="off" required readonly disabled class="table-input-text" name="PurchaseHistories[@anA].DatePurchase" value="@item.DatePurchase.ToString("yyyy-MM-dd")"></td>

                            </tr>

                            anI++;
                            anA++;
                        }
                    </tbody>
                </table>

            </form>
        </div>
        <div class="table_page ">
            <table>
                <thead>
                    <tr>
                        <th><input class="btn-tb" id="LinkChartId" type="submit" value="Отчёт" /></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div class="table_page ">

            <canvas id="myChart"></canvas>
            <canvas id="myChart2"></canvas>
            @for (int i = 0; i < Model.CharVM.Dates.Count; i++)
            {
                <input name="charDates" hidden value="@Model.CharVM.Dates[i]" />
                <input name="charPrices" hidden value="@Model.CharVM.Prices[i]" />
                <input name="charAmounts" hidden value="@Model.CharVM.Amounts[i]" />
            }

        </div>
    }
    else if (Model?.PurchaseHistories?.Count == 0 && Model.PurchaseHistories != null)
    {
        <div class="table_page ">
            <h4>Нет данных за эти месяцы</h4>
        </div>

    }
</div>
<script>

    document.getElementById("LinkChartId").onclick = function () {
        document.getElementById("formChartId").submit();
    }


    let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

    for (var item of ulActiveAs) {
        if (item.id == 'analyticsId') {
            item.classList.add("active");
        }
    }

</script>

App/OnlineStore/OnlineStore/Views/Superuser/EditPurchaseHistory.cshtml
@model EditPurchaseHistoryVM
@{ 
    int purI = 1;
    int purA = 0;
    Layout = "_LayoutAdmin";
}

<div class="tab-pane fade show active mx-auto col-md-10" id="purchaseHistory">
    <h4>История покупок</h4>

    <div class="table_page">
        <form asp-action="EditPurchaseHistory" asp-controller="Superuser">
            <table>
                <thead>
                    <tr>
                        <th>Клиент</th>
                        <th>Продукт</th>
                        <th>Количество</th>
                        <th>Дата покупки</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <select required class="select-f" readonly name="UserId">
                                @foreach (var user in Model.Users)
                                {
                                    <option class="select-option-f" value="@user.Id">@user.LastName @user.FirstName</option>
                                }
                            </select>
                        </td>
                        <td>
                            <select required class="select-f" readonly name="ProductId">
                                @foreach (var products in Model.Products)
                                {
                                    <option class="select-option-f" value="@products.Id">@products.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input type="number" min="1" max="99" autocomplete="off" required class="table-input-text" name="AmountProduct">
                        </td>
                        <td><input type="date" autocomplete="off" required class="table-input-text" name="DatePurchase"></td>
                        <td>
                            <input class="btn-tb" type="submit" value="Добавить" />
                        </td>
                    </tr>

            </table>
        </form>
    </div>

    <div class="table_page " style="overflow-x: auto;height: 400px;">

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Клиент</th>
                    <th>Продукт</th>
                    <th>Количество</th>
                    <th>Дата покупки</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PurchaseHistories)
                {
                    <form asp-action="EditPurchaseHistory" asp-controller="Superuser">
                    <tr id="trPurId-@purA">
                        <td>@purI</td>
                        <td>
                            <input hidden name="Id" value="@item.Id" />
                            <select required disabled class="select-f" readonly name="UserId" asp-for="PurchaseHistories[purA].UserId">
                                @foreach (var user in Model.Users)
                                {
                                    <option class="select-option-f" value="@user.Id">@user.LastName @user.FirstName</option>
                                }
                            </select>
                        </td>
                        <td>
                            <select required disabled class="select-f" readonly name="ProductId" asp-for="PurchaseHistories[purA].ProductId">
                                @foreach (var products in Model.Products)
                                {
                                    <option class="select-option-f" value="@products.Id">@products.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input type="number" autocomplete="off" min="1" max="99" required readonly class="table-input-text" name="AmountProduct" value="@item.AmountProduct">
                        </td>
                        <td><input type="date" autocomplete="off" required readonly class="table-input-text" name="DatePurchase" value="@item.DatePurchase.ToString("yyyy-MM-dd")"></td>

                        <td>
                            <input class="btn-tb" type="button" name="edit" onclick="Edit(this)" value="Редактировать" />
                            <input class="btn-tb" name="save" type="submit" onclick="Save(this)" style="display: none" value="Сохранить" />
                        </td>
                        <td>
                            <a class="btn-tb" href="@Url.Action("RemovePurchaseHistory", "Superuser", item)">Удалить</a>
                        </td>
                    </tr>
                    </form>
                    purI++;
                    purA++;
                }
            </tbody>
        </table>

    </div>

</div>
<script>
    let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

    for (var item of ulActiveAs) {
        if (item.id == 'purchaseHistoryId') {
            item.classList.add("active");
        }
    }

</script>

App/OnlineStore/OnlineStore/Views/Superuser/EditUser.cshtml
@model EditUserVM
@{ 
    int usI = 1;
    int usA = 0;
    Layout = "_LayoutAdmin";
}

<div class="tab-pane fade show active" id="user">
    <h4>Пользователи</h4>

    <div class="table_page">
        <form asp-action="EditUser" asp-controller="Superuser">
            <table>
                <thead>
                    <tr>
                        <th>Фамилия</th>
                        <th>Имя</th>
                        <th>Почта</th>
                        <th>Пароль</th>
                        <th>Телефон</th>
                        <th>Дата регистрации</th>
                        <th>Роль</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="text" autocomplete="off" required class="table-input-text" name="LastName">
                        </td>
                        <td>
                            <input type="text" autocomplete="off" required class="table-input-text" name="FirstName">
                        </td>
                        <td>
                            <input type="email" autocomplete="off" required class="table-input-text" name="Email">
                        </td>
                        <td>
                            <input type="password" autocomplete="off" required class="table-input-text" name="Password">
                        </td>
                        <td>
                            <input type="tel" autocomplete="off" required class="table-input-text" name="Phone">
                        </td>
                        <td><input type="date" autocomplete="off" required class="table-input-text" name="RegistrationDate"></td>
                        <td>
                            <select required class="select-f" readonly name="RoleId">
                                @foreach (var role in Model.Roles)
                                {
                                    <option class="select-option-f" value="@role.Id">@role.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input class="btn-tb" type="submit" value="Добавить" />
                        </td>
                    </tr>

            </table>
        </form>
    </div>

    <div class="table_page " style="overflow-x: auto;height: 400px;">

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Почта</th>
                    <th>Пароль</th>
                    <th>Телефон</th>
                    <th>Дата регистрации</th>
                    <th>Роль</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Users)
                {
                    <form asp-action="EditUser" asp-controller="Superuser">
                    <tr id="trUsrId-@usA">
                        <td>@usI</td>
                        <td>
                            <input hidden name="Id" value="@item.Id" />
                            <input type="text" autocomplete="off" required readonly class="table-input-text" name="LastName" value="@item.LastName">
                        </td>
                        <td>
                            <input type="text" autocomplete="off" required readonly class="table-input-text" name="FirstName" value="@item.FirstName">
                        </td>
                        <td>
                            <input type="email" autocomplete="off" required readonly class="table-input-text" name="Email" value="@item.Email">
                        </td>
                        <td>
                            <input type="password" autocomplete="off" required readonly class="table-input-text" name="Password" value="@item.Password">
                        </td>
                        <td>
                            <input type="tel" autocomplete="off" required readonly class="table-input-text" name="Phone" value="@item.Phone">
                        </td>
                        <td><input type="date" autocomplete="off" required readonly class="table-input-text" name="RegistrationDate" value="@item.RegistrationDate.ToString("yyyy-MM-dd")"></td>
                        <td>
                            <select required disabled class="select-f" readonly name="RoleId" asp-for="Users[usA].RoleId">
                                @foreach (var role in Model.Roles)
                                {
                                    <option class="select-option-f" value="@role.Id">@role.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <select required disabled class="select-f" readonly name="OnSale" asp-for="Users[usA].OnSale">

                                <option class="select-option-f" value="true">Виден</option>
                                <option class="select-option-f" value="false">Скрыт</option>

                            </select>
                        </td>
                        <td>
                            <input class="btn-tb" type="button" name="edit" onclick="Edit(this)" value="Редактировать" />
                            <input class="btn-tb" name="save" type="submit" onclick="Save(this)" style="display: none" value="Сохранить" />
                        </td>
                    </tr>
                    </form>
                    usI++;
                    usA++;
                }
            </tbody>
        </table>

    </div>

</div>
<script>
    let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

    for (var item of ulActiveAs) {
        if (item.id == 'userId') {
            item.classList.add("active");
        }
    }

</script>

App/OnlineStore/OnlineStore/Views/Superuser/Report.cshtml
@model ReportVM
@{
    Layout = null;
    int i = 1;
    int a = 0;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/myStyle.css">
</head>
<body>
    <div class="account_dashboard mt-10">
        <div class="container" style="max-width: 1800px;">
            <div class="row">
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <a id="back" class="btn btn-dark mt-2 ms-2" href="@Url.Action("Analytics","Superuser",Model)"> Назад</a>
                </div>
                <div class="mx-auto col-md-8">
                    <div class="position-absolute top-0 end-0">@DateTime.Now.ToString("D")</div>
                    <h3 class="mt-10">Отчёт по продажам</h3>
                    <h4 class="mt-10">За период с @Model.StartDate.ToString("D") по @Model.EndDate.ToString("D")</h4>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Клиент</th>
                                <th>Продукт</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Дата покупки</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PurchaseHistories)
                            {
                                <tr id="trPurId-@a">
                                    <td>@i</td>
                                    <td>
                                        <input hidden name="Id" value="@item.Id" />
                                        <input type="text" autocomplete="off" required readonly class="table-input-text" name="AmountProduct" value="@item.User.LastName @item.User.FirstName">
                                    </td>
                                    <td>
                                        <input type="text" hidden name="Id" value="@item.Product.Price" />
                                        <input type="text" autocomplete="off" required readonly class="table-input-text" name="Product.Name" value="@item.Product.Name">
                                    </td>
                                    <td>
                                        <input type="text" autocomplete="off" required readonly class="table-input-text" name="Product.Price" value="@item.Product.Price">
                                    </td>
                                    <td>
                                        <input type="text" autocomplete="off" required readonly class="table-input-text" name="AmountProduct" value="@item.AmountProduct">
                                    </td>
                                    <td><input type="date" autocomplete="off" required readonly class="table-input-text" name="DatePurchase" value="@item.DatePurchase.ToString("yyyy-MM-dd")"></td>

                                </tr>
                                a++;
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById("back").style.display = "none";
        window.print();
        setTimeout(() => { document.getElementById("back").style.display = "block" }, 2000);
    </script>
</body>
</html>