App/OnlineStore/OnlineStore/Controllers/ShoppingController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using OnlineStore.Data;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using OnlineStore.Models.SortPhilPag;
using System.Threading.Tasks;
using OnlineStore.Models.StaticModels;

namespace OnlineStore.Controllers
{
    public class ShoppingController : Controller
    {
        private readonly OnlineStore_DbContext db;
        public ShoppingController(OnlineStore_DbContext db)
        {
            this.db = db;
        }

        [HttpGet]
        public async Task<IActionResult> ShowProducts(Category category, List<Characteristic> characteristics, string priceFiltr = "1000 P - 3000 P", SortState sortOrder = SortState.NameAsc, int page = 1)
        {
            string[] stringArr = new string[6];
            if (priceFiltr != null)
                stringArr = priceFiltr.Split(new char[] { ' ' });

            category = await db.Categories.Where(c=>c.OnSale == true).FirstOrDefaultAsync(c => c.Id == category.Id);

            if (User.Identity.IsAuthenticated)
            {
                var userId = int.Parse(User.Claims.First().Value);
                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }

            List<Product> products = new();

            if (category == null || category.CategoryId == null && category.Id == 0)
                products = await db.Products.Where(p => p.OnSale == true).Include(p => p.Pictures).Include(p => p.ProductCharacteristics).ThenInclude(p => p.Characteristic).ToListAsync();
            else if (category.CategoryId == null)
            {
                var categories = await db.Categories.Where(c => c.CategoryId == category.Id && c.OnSale == true).ToListAsync();

                foreach (var item in categories)
                {
                    var categoriesList = await db.Products.Where(p => p.CategoryId == item.Id && p.OnSale==true).Include(p => p.Pictures).Include(p => p.ProductCharacteristics).ThenInclude(p => p.Characteristic).ToListAsync();
                    products.AddRange(categoriesList);
                }
            }
            else
                products = await db.Products.Where(p => p.CategoryId == category.Id && p.OnSale == true).Include(p => p.Pictures).Include(p => p.ProductCharacteristics).ThenInclude(p => p.Characteristic).ToListAsync();

            var showProductsVM = new ShowProductsVM();

            //Фильтрация
            var productsF = new List<Product>();
            if (characteristics == null || characteristics.Count() == 0)
                productsF = products;
            else
                foreach (var item in characteristics)
                {
                    productsF.AddRange(products.Where(p => p.ProductCharacteristics.Any(ph => ph.CharacteristicId == item.Id) == true));
                }

            if (stringArr[0] != null && stringArr[3] != null)
                productsF = productsF.Where(p => p.Price >= int.Parse(stringArr[0]) && p.Price <= int.Parse(stringArr[3])).ToList();

            //Сортировка
            productsF = sortOrder switch
            {
                SortState.NameAsc => productsF.OrderBy(s => s.Name).ToList(),
                SortState.NameDesc => productsF.OrderByDescending(s => s.Name).ToList(),
                SortState.PriceAsc => productsF.OrderBy(s => s.Price).ToList(),
                SortState.PriceDesc => productsF.OrderByDescending(s => s.Price).ToList(),
                _ => productsF.OrderBy(s => s.Name).ToList(),
            };

            showProductsVM.CoutProduct = productsF.Count;

            //Пагинация
            int pageSize = 9;
            var count = productsF.Count;
            productsF = productsF.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            showProductsVM.Products = productsF;
            showProductsVM.Category = category;
            showProductsVM.CheckedCharacteristics = characteristics;
            showProductsVM.Characteristics = db.Characteristics.ToList();
            showProductsVM.SortOrder = sortOrder;
            showProductsVM.PageVM = new PageViewModel(count, page, pageSize);
            showProductsVM.PriceFiltr = stringArr[0] + " P - " + stringArr[3] + " P";


            return View(showProductsVM);
        }

        [HttpGet]
        public async Task<IActionResult> ShowProduct(Product product)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = int.Parse(User.Claims.First().Value);
                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }

            var characteristics = await db.ProductCharacteristics.Where(p => p.ProductId == product.Id)
                .Include(p => p.Characteristic).Select(p => p.Characteristic).ToListAsync();

            var productVM = new ShowProductVM
            {
                Id = product.Id,
                Name = product.Name,
                CategoryId = product.CategoryId,
                Characteristics = characteristics,
                Pictures = await db.Pictures.Where(p => p.ProductId == product.Id).ToListAsync(),
                Category = product.Category,
                Price = product.Price,
                Rating = product.Rating
            };

            return View(productVM);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> AddToBasket(AddToBasketVM addToBasketVM)
        {

            var userId = int.Parse(User.Claims.First().Value);

            var category = await db.Categories.Where(c => c.OnSale == true).FirstOrDefaultAsync(c => c.Id == addToBasketVM.CategoryId);

            var basket = await db.Baskets.FirstOrDefaultAsync(c => c.UserId == userId);


            if (basket == null)
            {
                basket = new Basket { UserId = userId, ProductId = addToBasketVM.ProductId, AmountProduct = addToBasketVM.AmountProduct };
                await db.Baskets.AddAsync(basket);
            }
            else
            {
                var basketProduct = await db.Baskets.FirstOrDefaultAsync(b => b.UserId == userId && b.ProductId == addToBasketVM.ProductId);

                if (basketProduct != null)
                {
                    basketProduct.AmountProduct += addToBasketVM.AmountProduct;
                    db.Entry(basketProduct).State = EntityState.Modified;
                }
                else
                {
                    basketProduct = new Basket { AmountProduct = addToBasketVM.AmountProduct, ProductId = addToBasketVM.ProductId, UserId = userId };
                    await db.Baskets.AddAsync(basketProduct);
                }

            }

            await db.SaveChangesAsync();

            if (User.Identity.IsAuthenticated)
            {
                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }

            return RedirectToAction("ShowProducts", category);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ShowBasket()
        {
            List<Basket> baskets = new();

            if (int.TryParse(User.Claims.First().Value, out int userId))
            {
                baskets = await db.Baskets.Where(b => b.UserId == userId).Include(b => b.User).Include(b => b.Product).ThenInclude(p => p.Pictures).ToListAsync();

                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }

            return View(new ShowBasketVM { Baskets = baskets });
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> RemoveBasket(Basket basket)
        {
            if (basket != null)
            {
                db.Baskets.Remove(basket);
                await db.SaveChangesAsync();

                var userId = int.Parse(User.Claims.First().Value);
                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }

            return RedirectToAction("ShowBasket");
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> BuyProducts(List<Basket> Baskets)
        {
            if (Baskets.Count > 0)
            {
                foreach (var item in Baskets)
                {
                    await db.PurchaseHistories.AddAsync(new PurchaseHistory
                    {
                        AmountProduct = (int)item.AmountProduct,
                        ProductId = item.ProductId,
                        UserId = item.UserId,
                        DatePurchase = DateTime.Now
                    });
                }
                db.Baskets.RemoveRange(Baskets);

                await db.SaveChangesAsync();

                var userId = int.Parse(User.Claims.First().Value);
                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            }
            return RedirectToAction("ShowBasket");
        }
    }
}

App/OnlineStore/OnlineStore/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Data;
using OnlineStore.Models.StaticModels;
using OnlineStore.Models.UserViewModels;
using OnlineStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Controllers
{
    public class UserController : Controller
    {
        private readonly OnlineStore_DbContext db;

        public UserController(OnlineStore_DbContext db)
        {
            this.db = db;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> MyAccount()
        {
            int userId = int.Parse(User.Claims.First().Value);

            User user = await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
            List<PurchaseHistory> purchaseHistories = await db.PurchaseHistories
                .Where(p => p.UserId == userId)
                .Include(p => p.Product)
                .ToListAsync();

            var myAccountVM = new MyAccountVM
            {
                PurchaseHistories = purchaseHistories,
                User = new RegisterViewModel
                {
                    Email = user.Email,
                    LastName = user.LastName,
                    Phone = user.Phone,
                    FirstName = user.FirstName,
                    Password = user.Password
                }
            };


            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(myAccountVM);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditAccount(RegisterViewModel model)
        {
            int userId = int.Parse(User.Claims.First().Value);
            if (ModelState.IsValid)
            {
                User user = await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
                user.Email = model.Email; 
                user.LastName = model.LastName; 
                user.Phone = model.Phone; 
                user.FirstName = model.FirstName; 
                user.Password = model.Password;

                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();

                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();

                return RedirectToAction("MyAccount");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");

                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();

                return View();
            }
        }
    }
}

App/OnlineStore/OnlineStore/Views/User/MyAccount.cshtml
@model MyAccountVM
@{
    int i = 1;
}

<form id="formId" method="post" asp-controller="Account" asp-action="Logout">

</form>
<div class="account_dashboard mt-10">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">

                <div class="dashboard_tab_button">
                    <ul role="tablist" class="nav flex-column dashboard-list">
                        <li> <a href="#orders" data-toggle="tab" class="nav-link active">Покупки</a></li>
                        <li><a href="#account-details" data-toggle="tab" class="nav-link">Данные учетной записи</a></li>
                        <li><a href="#" id="linkId" class="nav-link">Выйти</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9">

                <div class="tab-content dashboard_content">
                    <div class="tab-pane fade show active" id="orders">
                        <h4>Покупки</h4>
                        <div class="table_page table-responsive">
                            <table>
                                <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Дата</th>
                                        <th>Товар</th>
                                        <th>Всего</th>
                                        <th>Показать</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.PurchaseHistories)
                                    {
                                        <tr>
                                            <td>@i</td>
                                            <td>@item.DatePurchase.ToString("D")</td>
                                            <td><span class="success">@item.Product.Name</span></td>
                                            <td>@Model.GetPrice(item.AmountProduct, item.Product.Price) ₽ за @item.AmountProduct товар </td>
                                            <td><a href="@Url.Action("ShowProduct","Shopping",item.Product)" class="view">Перейти</a></td>
                                        </tr>
                                        i++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-details">
                        <h3>Данные учетной записи</h3>
                        <div class="login">
                            <div class="login_form_container">
                                <div class="account_login_form">
                                    <form method="get" asp-action="EditAccount" asp-controller="User">
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="User.LastName" class="val"></span>
                                            <label>Фамилия <span>*</span></label>
                                            <input type="text" asp-for="User.LastName" name="LastName" placeholder="Фамилия" autofocus="">
                                        </div>
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="User.FirstName" class="val"></span>
                                            <label>Имя <span>*</span></label>
                                            <input type="text" asp-for="User.FirstName" name="FirstName" placeholder="Имя">
                                        </div>
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="User.Email" class="val"></span>
                                            <label>Email <span>*</span></label>
                                            <input type="email" asp-for="User.Email" name="Email" placeholder="Email">

                                        </div>
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="User.Phone" class="val"></span>
                                            <label>Телефон <span>*</span></label>
                                            <input type="tel" asp-for="User.Phone" name="Phone" placeholder="+71112223344">
                                        </div>
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="User.Password" class="val"></span>
                                            <label>Пароль <span>*</span></label>
                                            <input type="password" asp-for="User.Password" name="Password">
                                        </div>
                                        <div class="default-form-box mb-20">
                                            <span asp-validation-for="@Model.User.PasswordConfirm" class="val"></span>
                                            <label>Подтвердить пароль <span>*</span></label>
                                            <input type="password" asp-for="@Model.User.PasswordConfirm" name="PasswordConfirm">
                                        </div>
                                        <div class="save_button primary_btn default_button">
                                            <button type="submit">Сохранить</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("linkId").onclick = function () {
        document.getElementById("formId").submit();
    }
</script>