App/OnlineStore/OnlineStore/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Data;
using OnlineStore.Models.AdminViewModels;
using OnlineStore.Models.UserViewModels;
using OnlineStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Controllers
{
    public class AdminController : Controller
    {
        private readonly OnlineStore_DbContext db;
        //private readonly int userId;
        public AdminController(OnlineStore_DbContext db)
        {
            this.db = db;
            //userId = int.Parse(User.Claims.First().Value);
        }

        #region AdminAccount
        [Authorize(Roles = "admin,superuser")]
        public async Task<IActionResult> AdminAccount(AdminVM adminVM)
        {
            int userId = int.Parse(User.Claims.First().Value);
            User user = await db.Users.FirstOrDefaultAsync(u => u.Id == userId);

            var myAccountVM = new AdminVM
            {
                User = new RegisterViewModel
                {
                    Email = user.Email,
                    LastName = user.LastName,
                    Phone = user.Phone,
                    FirstName = user.FirstName,
                    Password = user.Password
                },
            };

            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(myAccountVM);
        }
        #endregion

        #region AdminShops
        [Authorize(Roles = "admin,superuser")]
        public async Task<IActionResult> AdminShops(AdminVM adminVM)
        {
            int userId = int.Parse(User.Claims.First().Value);
            List<PurchaseHistory> userPurchaseHistories = await db.PurchaseHistories
                .Where(p => p.UserId == userId)
                .Include(p => p.Product)
                .ToListAsync();

            var myAccountVM = new AdminVM
            {
                UserPurchaseHistories = userPurchaseHistories
            };

            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(myAccountVM);
        }
        #endregion

        #region Product

        [Authorize(Roles = "admin,superuser")]
        [HttpGet]
        public async Task<IActionResult> EditProduct()
        {
            List<Product> products = await db.Products.Include(p => p.Category).Include(p => p.ProductCharacteristics).ToListAsync();
            List<ProductVM> productVMs = new();

            foreach (Product product in products)
            {
                productVMs.Add(
                    new ProductVM
                    {
                        Id = product.Id,
                        ProductCharacteristics = product.ProductCharacteristics.Select(pc => pc.CharacteristicId).ToList(),
                        Category = product.Category,
                        CategoryId = product.CategoryId,
                        Description = product.Description,
                        Name = product.Name,
                        OnSale = product.OnSale,
                        Price = product.Price,
                        Rating = product.Rating,
                    });
            }
            List<Characteristic> characteristics = await db.Characteristics.ToListAsync();
            List<Category> productCategories = await db.Categories.Where(c => c.CategoryId != null && c.OnSale != false).ToListAsync();

            var editProductVM = new EditProductVM
            {
                Products = productVMs,
                ProductCategories = productCategories,
                Characteristics = characteristics,
            };
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(editProductVM);
        }

        [Authorize(Roles = "admin,superuser")]
        [HttpPost]
        public async Task<IActionResult> EditProduct(ProductVM product)
        {
            var pr = await db.Products.Include(p => p.ProductCharacteristics).FirstOrDefaultAsync(p => p.Id == product.Id);

            if (pr == null)
                pr = new Product();
            else
                pr.ProductCharacteristics.Clear();

            pr.Id = product.Id;
            pr.Category = product.Category;
            pr.CategoryId = product.CategoryId;
            pr.Description = product.Description;
            pr.Name = product.Name;
            pr.OnSale = product.OnSale;
            pr.Price = product.Price;
            pr.Rating = product.Rating;

            if (product.ProductCharacteristics != null)
                foreach (var item in product.ProductCharacteristics)
                {
                    pr.ProductCharacteristics.Add(new ProductCharacteristic { CharacteristicId = item, ProductId = product.Id });
                }


            if (pr.Id != 0)
            {
                db.Entry(pr).State = EntityState.Modified;
            }
            else
            {
                await db.Products.AddAsync(pr);
            }
            await db.SaveChangesAsync();

            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditProduct");
        }
        #endregion

        #region Category

        [Authorize(Roles = "admin,superuser")]
        [HttpGet]
        public async Task<IActionResult> EditCategory()
        {
            List<Category> categories = await db.Categories.ToListAsync();
            List<Category> parentCategories = await db.Categories.Where(c => c.CategoryId == null).ToListAsync();

            var editCategoryVM = new EditCategoryVM
            {
                ParentCategories = parentCategories,
                Categories = categories
            };

            return View(editCategoryVM);
        }

        [Authorize(Roles = "admin,superuser")]
        [HttpPost]
        public async Task<IActionResult> EditCategory(Category category)
        {
            if (category.CategoryId == 0)
                category.CategoryId = null;

            if (category.Id != 0)
            {
                db.Entry(category).State = EntityState.Modified;
            }
            else
            {
                await db.Categories.AddAsync(category);
            }
            await db.SaveChangesAsync();
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditCategory");
        }
        #endregion

        #region Characteristic

        [Authorize(Roles = "admin,superuser")]
        [HttpGet]
        public async Task<IActionResult> EditCharacteristic()
        {
            List<Characteristic> characteristics = await db.Characteristics.ToListAsync();

            var editCharacteristicVM = new EditCharacteristicVM
            {
                Characteristics = characteristics,
            };
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(editCharacteristicVM);
        }

        [Authorize(Roles = "admin,superuser")]
        [HttpPost]
        public async Task<IActionResult> EditCharacteristic(Characteristic characteristic)
        {

            if (characteristic.Id != 0)
            {
                db.Entry(characteristic).State = EntityState.Modified;
            }
            else
            {
                await db.Characteristics.AddAsync(characteristic);
            }
            await db.SaveChangesAsync();
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditCharacteristic");
        }
        [Authorize(Roles = "admin,superuser")]
        [HttpGet]
        public async Task<IActionResult> RemoveCharacteristic(Characteristic characteristic)
        {

            if (characteristic.Id != 0)
            {
                var chPrs = db.ProductCharacteristics.Where(pc => pc.CharacteristicId == characteristic.Id);
                db.RemoveRange(chPrs);
                db.Remove(characteristic);
                await db.SaveChangesAsync();
            }
            int userId = int.Parse(User.Claims.First().Value);
            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return RedirectToAction("EditCharacteristic");
        }
        #endregion

        #region Picture

        [Authorize(Roles = "admin,superuser")]
        [HttpGet]
        public async Task<IActionResult> EditPicture()
        {
            List<Product> products = await db.Products.Include(p => p.Category).Include(p => p.ProductCharacteristics).ToListAsync();
            List<ProductVM> productVMs = new();

            foreach (Product product in products)
            {
                productVMs.Add(
                    new ProductVM
                    {
                        Id = product.Id,
                        ProductCharacteristics = product.ProductCharacteristics.Select(pc => pc.CharacteristicId).ToList(),
                        Category = product.Category,
                        CategoryId = product.CategoryId,
                        Description = product.Description,
                        Name = product.Name,
                        OnSale = product.OnSale,
                        Price = product.Price,
                        Rating = product.Rating,
                    });
            }

App/OnlineStore/OnlineStore/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Data;
using OnlineStore.Models.StaticModels;
using OnlineStore.Models.UserViewModels;
using OnlineStore.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Controllers
{
    public class UserController : Controller
    {
        private readonly OnlineStore_DbContext db;

        public UserController(OnlineStore_DbContext db)
        {
            this.db = db;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> MyAccount()
        {
            int userId = int.Parse(User.Claims.First().Value);

            User user = await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
            List<PurchaseHistory> purchaseHistories = await db.PurchaseHistories
                .Where(p => p.UserId == userId)
                .Include(p => p.Product)
                .ToListAsync();

            var myAccountVM = new MyAccountVM
            {
                PurchaseHistories = purchaseHistories,
                User = new RegisterViewModel
                {
                    Email = user.Email,
                    LastName = user.LastName,
                    Phone = user.Phone,
                    FirstName = user.FirstName,
                    Password = user.Password
                }
            };


            ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();
            return View(myAccountVM);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditAccount(RegisterViewModel model)
        {
            int userId = int.Parse(User.Claims.First().Value);
            if (ModelState.IsValid)
            {
                User user = await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
                user.Email = model.Email; 
                user.LastName = model.LastName; 
                user.Phone = model.Phone; 
                user.FirstName = model.FirstName; 
                user.Password = model.Password;

                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();

                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();

                return RedirectToAction("MyAccount");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");

                ViewData["AmountBasket"] = await db.Baskets.Where(b => b.UserId == userId).CountAsync();

                return View();
            }
        }
    }
}

App/OnlineStore/OnlineStore/Views/Admin/AdminAccount.cshtml
@model AdminVM
@{
    Layout = "_LayoutAdmin";
}

<div class="tab-pane fade show active mx-auto col-md-8" id="account-details">
    <h3>Данные учетной записи</h3>
    <div class="login">
        <div class="login_form_container">
            <div class="account_login_form">
                <form method="get" asp-action="EditAccount" asp-controller="User">
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="User.LastName" class="val"></span>
                        <label>Фамилия <span>*</span></label>
                        <input type="text" asp-for="User.LastName" name="LastName" placeholder="Фамилия" autofocus="">
                    </div>
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="User.FirstName" class="val"></span>
                        <label>Имя <span>*</span></label>
                        <input type="text" asp-for="User.FirstName" name="FirstName" placeholder="Имя">
                    </div>
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="User.Email" class="val"></span>
                        <label>Email <span>*</span></label>
                        <input type="email" asp-for="User.Email" name="Email" placeholder="Email">

                    </div>
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="User.Phone" class="val"></span>
                        <label>Телефон <span>*</span></label>
                        <input type="tel" asp-for="User.Phone" name="Phone" placeholder="+71112223344">
                    </div>
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="User.Password" class="val"></span>
                        <label>Пароль <span>*</span></label>
                        <input type="password" asp-for="User.Password" name="Password">
                    </div>
                    <div class="default-form-box mb-20">
                        <span asp-validation-for="@Model.User.PasswordConfirm" class="val"></span>
                        <label>Подтвердить пароль <span>*</span></label>
                        <input type="password" asp-for="@Model.User.PasswordConfirm" name="PasswordConfirm">
                    </div>
                    <div class="save_button primary_btn default_button">
                        <button type="submit">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
        let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

        for (var item of ulActiveAs) {
            if (item.id == 'account-detailsId') {
                item.classList.add("active");
            }
        }

</script>

App/OnlineStore/OnlineStore/Views/Admin/AdminShops.cshtml
@model AdminVM
@{
    int i = 1;
    Layout = "_LayoutAdmin";
}
<div class="tab-pane fade show active" id="shops">
    <h4>Покупки</h4>
    <div class="table_page table-responsive">
        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Дата</th>
                    <th>Товар</th>
                    <th>Всего</th>
                    <th>Показать</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.UserPurchaseHistories)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.DatePurchase.ToString("D")</td>
                        <td><span class="success">@item.Product.Name</span></td>
                        <td>@Model.GetPrice(item.AmountProduct, item.Product.Price) ₽ за @item.AmountProduct товар </td>
                        <td><a href="@Url.Action("ShowProduct","Shopping",item.Product)" class="view">Перейти</a></td>
                    </tr>
                    i++;
                }
            </tbody>
        </table>
    </div>
</div>
<script>
        let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

        for (var item of ulActiveAs) {
            if (item.id == 'shopsId') {
                item.classList.add("active");
            }
        }

</script>

App/OnlineStore/OnlineStore/Views/Admin/EditCategory.cshtml
@model EditCategoryVM
@{
    int cI = 1;
    int cA = 0;
    Layout = "_LayoutAdmin";
}
<div class="tab-pane fade show active mx-auto col-md-10" id="categories">
    <h4>Товары</h4>

    <div class="table_page">
        <form asp-action="EditCategory" asp-controller="Admin">
            <table>
                <thead>
                    <tr>
                        <th>Название</th>
                        <th>Родитель</th>
                        <th>Статус</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="text" autocomplete="off" required class="table-input-text input-selected" name="Name">
                        </td>
                        <td>
                            <select required class="select-f" readonly name="CategoryId">
                                <option class="select-option-f">Нет</option>
                                @foreach (var category in Model.ParentCategories)
                                {
                                    <option class="select-option-f" value="@category.Id">@category.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <select required class="select-f" readonly name="OnSale">

                                <option class="select-option-f" value="true">Виден</option>
                                <option class="select-option-f" value="false">Скрыт</option>

                            </select>
                        </td>
                        <td>
                            <input class="btn-tb" type="submit" value="Добавить" />
                        </td>
                    </tr>
            </table>
        </form>
    </div>

    <div class="table_page " style="overflow-x: auto;height: 400px;">

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Родитель</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Categories)
                {
                    <form asp-action="EditCategory" asp-controller="Admin">
                    <tr id="trCatId-@cA">
                        <td>@cI</td>
                        <td>
                            <input hidden name="Id" value="@item.Id" />
                            <input type="text" autocomplete="off" required readonly class="table-input-text" name="Name" value="@item.Name">
                        </td>
                        <td>
                            <select required disabled class="select-f" name="CategoryId" asp-for="Categories[cA].CategoryId">
                                <option class="" value="0">Нет</option>
                                @foreach (var category in Model.ParentCategories)
                                {
                                    <option class="" value="@category.Id">@category.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <select required disabled class="select-f" readonly name="OnSale" asp-for="Categories[cA].OnSale">

                                <option class="select-option-f" value="@bool.TrueString">Виден</option>
                                <option class="select-option-f" value="@bool.FalseString">Скрыт</option>

                            </select>
                        </td>

                        <td>
                            <input class="btn-tb" type="button" name="edit" onclick="Edit(this)" value="Редактировать" />
                            <input class="btn-tb" name="save" type="submit" onclick="Save(this)" style="display: none" value="Сохранить" />
                        </td>
                    </tr>
                    </form>
                    cI++;
                    cA++;
                }
            </tbody>
        </table>

    </div>

    <script>
        let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

        for (var item of ulActiveAs) {
            if (item.id == 'categoriesId') {
                item.classList.add("active");
            }
        }

    </script>
</div>

App/OnlineStore/OnlineStore/Views/Admin/EditCharacteristic.cshtml
@model EditCharacteristicVM
@{ 
    int chI = 1;
    int chA = 0;
    Layout = "_LayoutAdmin";
}

<div class="tab-pane fade show active mx-auto col-md-10" id="characteristic">
    <h4>Характеристики</h4>

    <div class="table_page">
        <form asp-action="EditCharacteristic" asp-controller="Admin">
            <table>
                <thead>
                    <tr>
                        <th>Название</th>
                        <th>Описание</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input hidden name="Id" />
                            <input type="text" autocomplete="off" required class="table-input-text" name="Name">
                        </td>
                        <td><input type="text" autocomplete="off" required class="table-input-text" name="Value"></td>
                        <td>
                            <input class="btn-tb" type="submit" value="Добавить" />
                        </td>
                    </tr>

            </table>
        </form>
    </div>

    <div class="table_page " style="overflow-x: auto;height: 400px;">

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Characteristics)
                {
                    <form asp-action="EditCharacteristic" asp-controller="Admin">
                    <tr id="trСhaId-@chA">
                        <td>@chI</td>
                        <td>
                            <input hidden name="Id" value="@item.Id" />
                            <input type="text" autocomplete="off" required readonly class="table-input-text" name="Name" value="@item.Name">
                        </td>
                        <td><input type="text" autocomplete="off" required readonly class="table-input-text" name="Value" value="@item.Value"></td>
                        <td>
                            <input class="btn-tb" type="button" name="edit" onclick="Edit(this)" value="Редактировать" />
                            <input class="btn-tb" name="save" type="submit" onclick="Save(this)" style="display: none" value="Сохранить" />
                        </td>
                        <td>
                            <a class="btn-tb" href="@Url.Action("RemoveCharacteristic","Admin",item)">Удалить</a>
                        </td>
                    </tr>
                    </form>
                    chI++;
                    chA++;
                }
            </tbody>
        </table>

    </div>

</div>

<script>
    let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

    for (var item of ulActiveAs) {
        if (item.id == 'characteristicId') {
            item.classList.add("active");
        }
    }

</script>

App/OnlineStore/OnlineStore/Views/Admin/EditPicture.cshtml
@model EditPictureVM
@{ 
    int piI = 1;
    int piA = 0;
    Layout = "_LayoutAdmin";
}

<div class="tab-pane fade show active mx-auto col-md-10" id="picture">
    <h4>Картинки</h4>

    <div class="table_page">
        <form asp-action="EditPicture" asp-controller="Admin">
            <table>
                <thead>
                    <tr>
                        <th>Название</th>
                        <th>Путь</th>
                        <th>Продукт</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input hidden name="Id" />
                            <input type="text" autocomplete="off" required class="table-input-text" name="Name">
                        </td>
                        <td><input type="text" autocomplete="off" required class="table-input-text" name="Path"></td>
                        <td>
                            <select required class="select-f" readonly name="ProductId">
                                <option class="select-option-f">Нет</option>
                                @foreach (var product in Model.Products)
                                {
                                    <option class="select-option-f" value="@product.Id">@product.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input class="btn-tb" type="submit" value="Добавить" />
                        </td>
                    </tr>

            </table>
        </form>
    </div>

    <div class="table_page " style="overflow-x: auto;height: 400px;">

        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Путь</th>
                    <th>Продукт</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Pictures)
                {
                    <form asp-action="EditPicture" asp-controller="Admin">
                    <tr id="trCatId-@piA">
                        <td>@piI</td>
                        <td>
                            <input hidden name="Id" value="@item.Id" />
                            <input type="text" autocomplete="off" required readonly class="table-input-text" name="Name" value="@item.Name">
                        </td>
                        <td><input type="text" autocomplete="off" readonly class="table-input-text" name="Path" value="@item.Path"></td>
                        <td>
                            <select required disabled class="select-f" readonly name="ProductId" asp-for="Pictures[piA].ProductId">
                                @foreach (var products in Model.Products)
                                {
                                    <option class="select-option-f" value="@products.Id">@products.Name</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input class="btn-tb" type="button" name="edit" onclick="Edit(this)" value="Редактировать" />
                            <input class="btn-tb" name="save" type="submit" onclick="Save(this)" style="display: none" value="Сохранить" />
                        </td>
                        <td>
                            <a class="btn-tb" href="@Url.Action("RemovePicture","Admin",item)">Удалить</a>
                        </td>
                    </tr>
                    </form>
                    piI++;
                    piA++;
                }
            </tbody>
        </table>

    </div>

</div>

<script>
    let ulActiveAs = document.getElementById("ulActive").getElementsByTagName("a");

    for (var item of ulActiveAs) {
        if (item.id == 'picturesId') {
            item.classList.add("active");
        }
    }

</script>